apiVersion : apps/v1
kind: Deployment
metadata:
  name: nickgulrajanipipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nickgulrajanipipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: nickgulrajanipipelinesjavascriptdocker 
    spec:
      containers:
        - name: nickgulrajanipipelinesjavascriptdocker 
          image: nicappcontainerregistry.azurecr.io/nickgulrajanipipelinesjavascriptdocker
          ports:
          - containerPort: 8080